name: kinderfrontend
description: dating app named kinder, swipe right to like, left to dislike

publish_to: "none" 
version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  cupertino_icons: ^1.0.2
  lottie: ^2.6.0
  provider: ^6.0.5
  fluttertoast: ^8.2.2
  cloud_firestore: ^4.9.3
  firebase_core: 2.17.0
  #firebase_auth: ^4.10.1
  intl_utils: ^2.8.12
  google_fonts: ^6.3.1

dev_dependencies:
  build_runner: ^2.3.0
  flutter_test:
    sdk: flutter

  

  flutter_lints: ^2.0.0

flutter:

  generate: true
  assets:
    - assets/chat_img.png
    - assets/profile_img.png
    - assets/martta.png
    - assets/like.png
    - assets/cancel.png
    - assets/arrow-back.png
    - assets/mock_data.json
    - assets/animation_clap.json
    - assets/animation_login.json

  uses-material-design: true

flutter_intl:
  enabled: true
